@localhost = http://localhost:8080

### Greet
GET {{localhost}}/greet HTTP/1.1

### Health Check
GET {{localhost}}/health HTTP/1.1

### Metrics
GET {{localhost}}/metrics HTTP/1.1
Accept: application/json

### Config
GET {{localhost}}/config/1 HTTP/1.1

### Config
GET {{localhost}}/config/2 HTTP/1.1