@localhost = http://localhost:8080

### Greet
GET {{localhost}}/greet HTTP/1.1

### Health Check
GET {{localhost}}/health HTTP/1.1

### Metrics
GET {{localhost}}/metrics HTTP/1.1
Accept: application/json

### Config
GET {{localhost}}/config HTTP/1.1

### OpenAPI
GET {{localhost}}/openapi HTTP/1.1

### OpenAPI implement Filter
GET {{localhost}}/openapi/test HTTP/1.1