openapi: 3.0.0
info:
  title: Helidon SE OpenAPI Example.
  description: helidon se openapi example.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server.

components:
  schemas:
    GreetingMessage:
      properties:
        message:
          type: string
    ConfigMessage:
      properties:
        message:
          type: string

paths:
  /greet:
    get:
      summary: Returns a generic greeting
      description: Greets the user generically
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                Greet:
                  value:
                    message: Hello World!
  /config:
    get:
      summary: Returns a config properties.
      description: return a config properties.
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                Config:
                  value:
                    message: config service works!!